# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-22 15:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=600, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('apellido_paterno', models.CharField(max_length=600)),
                ('apellido_materno', models.CharField(max_length=600)),
                ('fecha_nacimiento', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('direccion', models.CharField(max_length=600)),
                ('tlf', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('foto', models.ImageField(upload_to='profiles/')),
                ('acta_nacimiento', models.ImageField(upload_to='actas_nacimiento/')),
                ('docu_ident_front', models.ImageField(upload_to='documentos_identidad/')),
                ('docu_ident_back', models.ImageField(blank=True, upload_to='documentos_identidad/')),
                ('pasaporte', models.IntegerField()),
                ('pasaporte_valido', models.DateTimeField(verbose_name='fecha de vencimiento')),
                ('pais_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_nacimiento_de', to='empleados.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nacionalidad_de', to='empleados.Country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_de', to='empleados.Empleado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=600, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento_identidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pais_nacimiento_de', to='empleados.TipoDocumentoIdentidad'),
        ),
    ]
