# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='imagen_pasaporte',
            field=models.ImageField(default=datetime.datetime(2018, 2, 24, 13, 0, 8, 135963), upload_to='pasaportes/'),
            preserve_default=False,
        ),
    ]
