# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_imagen_pasaporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
